language:
  - node_js
node_js:
  - "0.10"
before_script:
  - export CONTINUOUS_INTEGRATION=true
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --ignore-scripts --quiet
after_script:
  - npm run coveralls
